### PR TITLE
Logic For Building Image on Additional Architectures

### PR DESCRIPTION
**Pull request by nerethos**
Added some logic to the dockerfile that determines the arch used for building and downloads the correct release from GitHub.

### CODE REVIEW

**Comment by Tarow** [comment]
The way that the docker image is being built is kind of strange imo.
I'd either write a Dockerfile that builds frontend+backend or use [Goreleaser to also build the docker image](https://goreleaser.com/customization/docker/), since Goreleaser is already being used anyways.

Using Goreleaser to build and publish the binaries, then have the Docker build step just download the binary from Github Releases seems kind of weird.

**Comment by nerethos** [comment]
> The way that the docker image is being built is kind of strange imo. I'd either write a Dockerfile that builds frontend+backend or use [Goreleaser to also build the docker image](https://goreleaser.com/customization/docker/), since Goreleaser is already being used anyways.
> 
> Using Goreleaser to build and publish the binaries, then have the Docker build step just download the binary from Github Releases seems kind of weird.

"Improved Dockerfile" might not be the best/correct title for the PR as I don't plan on making any additional changes. I only created the PR because I made this same change locally so that I could build on any of my lab devices.

**Comment by Tarow** [comment]
Fair point, it's definitely an improvement.

Maybe long term the whole pipeline can be changed.
Looking at Github actions i think the current behavior is kind of bugged.

Docker-Action runs on every push to main and downloads the latest release every time (which only gets created on every tag).
When a new tag is pushed, the Docker-Action will most likely win that race condition and download the previous release before the Release action finishes. I don't want to complain too much tho, just some thoughts that came up looking at the code.

**Comment by nerethos** [comment]
>When a new tag is pushed, the Docker-Action will most likely win that race condition and download the previous release before the Release action finishes.

That's a good point that I hadn't considered.

Ultimately the docker image should probably be released and distributed in the same flow as the binaries, but I think that'll need a new PR 😄

**Comment by nerethos** [comment]
>When a new tag is pushed, the Docker-Action will most likely win that race condition and download the previous release before the Release action finishes.

That's a good point that I hadn't considered.

Ultimately the docker image should probably be released and distributed in the same flow as the binaries, but I think that'll need a new PR 😄

**Comment by meauxt** [comment]
Thank you for the change @nerethos ! @Tarow, @nerethos  please feel free to raise PR with any pipeline improvement!

**Pull request merged**
